import { Geist, Geist_Mono } from "next/font/google";
import { Battambang } from "next/font/google"; // Import the Battambang font
import "@/styles/style.scss"; // Global style

// Import the Phosphor Icons stylesheet
import "@phosphor-icons/web/duotone/style.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configure the Battambang font
const battambang = Battambang({
  subsets: ["khmer"],
  weight: ["400", "700"], // Regular and Bold weights
  variable: "--font-battambang",
});

export const metadata = {
  title: "Software Factory",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // Add the Battambang font variable to the html tag
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${battambang.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
