import { Geist, Geist_Mono } from "next/font/google";
import { Battambang } from "next/font/google";
import "@/styles/style.scss";
import "@phosphor-icons/web/duotone/style.css";

// Component
import TelegramFloat from "@/components/TelegramChat/TelegramFloat";
import Menu from "@/components/Header/Menu/Menu";
import Footer from "@/components/Footer/Footer";
// import TopNav from "@/components/Header/TopNav/TopNav";

import { getSettingData } from "@/lib/data/setting";
import { getMenuData } from "@/lib/data/menu";
import { getFooterData } from "@/lib/data/footer";
// import { getTopNavData } from "@/lib/data/topnav";

// Initializes the Geist Sans and Mono fonts for use throughout the application.
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Initializes the Battambang font, specifically for displaying Khmer characters.
const battambang = Battambang({
  subsets: ["khmer"],
  weight: ["400", "700"],
  variable: "--font-battambang",
});

// A Next.js function that dynamically generates metadata (like title and description) for SEO purposes.
export async function generateMetadata() {
  const settings = await getSettingData();
  const siteTitle = settings?.site_title || "Anajak Software";
  return {
    title: { template: `%s | ${siteTitle}`, default: siteTitle },
    description: settings?.site_tagline || "Generated by create next app",
    icons: { icon: settings?.favicon_url || "/AnajakSoftware-Favicon.png" },
  };
}

export default async function RootLayout({ children }) {

  const [
    // topNavData,
    menuData,
    footerData,
  ] = await Promise.all([
    // getTopNavData(),
    getMenuData(),
    getFooterData(),
  ]);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${battambang.variable} antialiased`}
      >
        <header id="header">
          {/* <TopNav data={topNavData} /> */}
          <Menu data={menuData} />
        </header>

        {/* The main content area where the content of individual pages will be rendered. */}
        <main className="content">{children}</main>

        {/* Defines the footer section of the layout. */}
        <footer id="footer">
          <Footer data={footerData} />
        </footer>

        {/* Renders the floating Telegram chat button component on all pages. */}
        <TelegramFloat />
      </body>
    </html>
  );
}