import { Geist, Geist_Mono } from "next/font/google";
import { Battambang } from "next/font/google";
import "@/styles/style.scss"; // Global style

import TelegramFloat from '@/components/TelegramChat/TelegramFloat'; 

// Import the Phosphor Icons stylesheet
import "@phosphor-icons/web/duotone/style.css";

// Import the new data-fetching function
import { getSettingData } from "@/lib/data/setting";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configure the Battambang font
const battambang = Battambang({
  subsets: ["khmer"],
  weight: ["400", "700"], // Regular and Bold weights
  variable: "--font-battambang",
});

// This function now dynamically generates the metadata
export async function generateMetadata() {
  const settings = await getSettingData();

  const siteTitle = settings?.site_title || "Anajak Software";

  return {
    // UPDATED: Use a title template
    title: {
      template: `%s | ${siteTitle}`,
      default: siteTitle, // The default title for the homepage
    },
    description: settings?.site_tagline || "Generated by create next app",
    icons: {
      icon: settings?.favicon_url || "/AnajakSoftware-Favicon.png",
    },
  };
}

export default function RootLayout({ children }) {
  return (
    // Add the Battambang font variable to the html tag
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${battambang.variable} antialiased`}
      >
        {children}

        {/* Telegram chat */}
        <TelegramFloat />
      </body>
    </html>
  );
}
